import { LogIn } from "lucide-react";

export const API = {
  AUTH: {
    REGISTER: "http://localhost:5050/api/auth/register",
    LOGIN: "http://localhost:5050/api/auth/login",
    WHOAMI: "http://localhost:5050/api/auth/whoami",
    UPDATE_PROFILE: "http://localhost:5050/api/auth/update-profile",
    REQUEST_PASSWORD_RESET: 'http://localhost:5050/api/auth/request-password-reset',
    RESET_PASSWORD: (token: string) => `http://localhost:5050/api/auth/reset-password/${token}`,
  },
  JOURNALS: {
    LIST: "http://localhost:5050/api/journals",
    CREATE: "http://localhost:5050/api/journals",
    GET: (id: string) => `http://localhost:5050/api/journals/${id}`,
    UPDATE: (id: string) => `http://localhost:5050/api/journals/${id}`,
    DELETE: (id: string) => `http://localhost:5050/api/journals/${id}`,
  },
  EXERCISES: {
    LIST: "http://localhost:5050/api/exercises",
    CREATE: "http://localhost:5050/api/exercises",
    GET: (id: string) => `http://localhost:5050/api/exercises/${id}`,
    UPDATE: (id: string) => `http://localhost:5050/api/exercises/${id}`,
    DELETE: (id: string) => `http://localhost:5050/api/exercises/${id}`,
    CLEAR_HISTORY: "http://localhost:5050/api/exercises/history",
    GUIDED_COMPLETE: "http://localhost:5050/api/exercises/guided/complete",
    GUIDED_HISTORY: "http://localhost:5050/api/exercises/guided/history",
  },
  MOODS: {
    LIST: "http://localhost:5050/api/moods",
    CREATE: "http://localhost:5050/api/moods",
    ANALYTICS: "http://localhost:5050/api/moods/analytics",
    OVERVIEW: "http://localhost:5050/api/moods/overview",
    BY_DATE: "http://localhost:5050/api/moods/by-date",
    RANGE: "http://localhost:5050/api/moods/range",
    GET: (id: string) => `http://localhost:5050/api/moods/${id}`,
    UPDATE: (id: string) => `http://localhost:5050/api/moods/${id}`,
    DELETE: (id: string) => `http://localhost:5050/api/moods/${id}`,
  },
  SCHEDULES: {
    LIST: "http://localhost:5050/api/schedules",
    CREATE: "http://localhost:5050/api/schedules",
    GET: (id: string) => `http://localhost:5050/api/schedules/${id}`,
    UPDATE: (id: string) => `http://localhost:5050/api/schedules/${id}`,
    DELETE: (id: string) => `http://localhost:5050/api/schedules/${id}`,
  },
  REMINDERS: {
    LIST: "http://localhost:5050/api/reminders",
    CREATE: "http://localhost:5050/api/reminders",
    GET: (id: string) => `http://localhost:5050/api/reminders/${id}`,
    UPDATE: (id: string) => `http://localhost:5050/api/reminders/${id}`,
    DELETE: (id: string) => `http://localhost:5050/api/reminders/${id}`,
    TOGGLE: (id: string) => `http://localhost:5050/api/reminders/${id}/toggle`,
    NOTIFICATIONS: (limit = 20) => `http://localhost:5050/api/reminders/notifications?limit=${limit}`,
    MARK_NOTIFICATION_READ: (id: string) => `http://localhost:5050/api/reminders/notifications/${id}/read`,
    MARK_ALL_NOTIFICATIONS_READ: "http://localhost:5050/api/reminders/notifications/read-all",
    CLEAR_NOTIFICATIONS: "http://localhost:5050/api/reminders/notifications",
    DUE: (windowMinutes = 2) => `http://localhost:5050/api/reminders/due?windowMinutes=${windowMinutes}`,
  },
  
};